baseURL         = "https://www.iheardata.com/"
languageCode    = "en-us"
title           = "Brian Gruber"
theme           = "cocoa"

[[menu.main]]
name            = "Bio"
url             = "/bio/"
[[menu.main]]
name            = "Projects"
url             = "/projects/"

[params]
author          = "Brian Gruber"
description     = "i hear data"

github          = "https://github.com/bgruber"
twitter         = "https://twitter.com/iheardata"
instagram       = "https://instagram.com/iheardata"
linkedin        = "https://linkedin.com/in/brian-gruber-73b6105/"

gravatar        = "15189314d09d28a33ceb753fa2b6741a"
